import SwiftUI
import ComposeApp

/// A bridge class that provides the root view controller to Kotlin for MSAL authentication
/// This is necessary because MSAL needs a UIViewController to present the login UI
@objc public class MSALViewControllerProvider: NSObject {

    @objc public static let shared = MSALViewControllerProvider()

    private override init() {
        super.init()
    }

    /// Get the root view controller for presenting MSAL login UI
    @objc public func getRootViewController() -> UIViewController? {
        // Get the key window's root view controller
        guard let scene = UIApplication.shared.connectedScenes.first as? UIWindowScene,
              let window = scene.windows.first else {
            return nil
        }

        var rootViewController = window.rootViewController

        // Traverse to find the topmost presented view controller
        while let presentedViewController = rootViewController?.presentedViewController {
            rootViewController = presentedViewController
        }

        return rootViewController
    }
}

/// Kotlin-callable wrapper for MSAL authentication
/// This class exposes simplified methods that can be called from Kotlin
@objc public class MSALKotlinBridge: NSObject {

    @objc public static let shared = MSALKotlinBridge()

    private override init() {
        super.init()
    }

    /// Initialize MSAL - call this when app starts
    @objc public func initialize(
        onAccountLoaded: @escaping (Bool) -> Void,
        onError: @escaping (String) -> Void
    ) {
        let callback = MSALCallbackImpl(
            onSuccessHandler: { _ in },
            onErrorHandler: onError,
            onAccountLoadedHandler: onAccountLoaded,
            onSignOutHandler: {}
        )

        // Use direct initialization (redirectUri will be auto-generated by MSAL based on bundle ID)
        MSALAuthHelper.shared.initialize(callback: callback)
    }

    /// Acquire token interactively - shows login UI
    @objc public func acquireToken(
        onSuccess: @escaping (String) -> Void,
        onError: @escaping (String) -> Void
    ) {
        guard let viewController = MSALViewControllerProvider.shared.getRootViewController() else {
            onError("Could not get root view controller")
            return
        }

        let callback = MSALCallbackImpl(
            onSuccessHandler: onSuccess,
            onErrorHandler: onError,
            onAccountLoadedHandler: { _ in },
            onSignOutHandler: {}
        )

        MSALAuthHelper.shared.acquireTokenInteractively(viewController: viewController, callback: callback)
    }

    /// Acquire token silently - for already logged in users
    @objc public func acquireTokenSilently(
        onSuccess: @escaping (String) -> Void,
        onError: @escaping (String) -> Void
    ) {
        let callback = MSALCallbackImpl(
            onSuccessHandler: onSuccess,
            onErrorHandler: onError,
            onAccountLoadedHandler: { _ in },
            onSignOutHandler: {}
        )

        MSALAuthHelper.shared.acquireTokenSilently(callback: callback)
    }

    /// Sign out the current user
    @objc public func signOut(
        onComplete: @escaping () -> Void,
        onError: @escaping (String) -> Void
    ) {
        let callback = MSALCallbackImpl(
            onSuccessHandler: { _ in },
            onErrorHandler: onError,
            onAccountLoadedHandler: { _ in },
            onSignOutHandler: onComplete
        )

        MSALAuthHelper.shared.signOut(callback: callback)
    }

    /// Check if user is signed in
    @objc public func isSignedIn() -> Bool {
        return MSALAuthHelper.shared.isSignedIn()
    }
}

/// Adapter that conforms to Kotlin's IOSMSALBridge protocol
/// This class bridges Swift's MSALKotlinBridge to Kotlin's expected interface
public class MSALBridgeAdapter: IOSMSALBridge {

    public static let shared = MSALBridgeAdapter()

    private init() {}

    public func initialize(onAccountLoaded: @escaping (KotlinBoolean) -> Void, onError: @escaping (String) -> Void) {
        MSALKotlinBridge.shared.initialize(
            onAccountLoaded: { hasAccount in
                onAccountLoaded(KotlinBoolean(bool: hasAccount))
            },
            onError: onError
        )
    }

    public func acquireToken(onSuccess: @escaping (String) -> Void, onError: @escaping (String) -> Void) {
        MSALKotlinBridge.shared.acquireToken(onSuccess: onSuccess, onError: onError)
    }

    public func acquireTokenSilently(onSuccess: @escaping (String) -> Void, onError: @escaping (String) -> Void) {
        MSALKotlinBridge.shared.acquireTokenSilently(onSuccess: onSuccess, onError: onError)
    }

    public func signOut(onComplete: @escaping () -> Void, onError: @escaping (String) -> Void) {
        MSALKotlinBridge.shared.signOut(onComplete: onComplete, onError: onError)
    }

    public func isSignedIn() -> Bool {
        return MSALKotlinBridge.shared.isSignedIn()
    }
}

/// Implementation of MSALAuthCallback using closures
private class MSALCallbackImpl: NSObject, MSALAuthCallback {

    private let onSuccessHandler: (String) -> Void
    private let onErrorHandler: (String) -> Void
    private let onAccountLoadedHandler: (Bool) -> Void
    private let onSignOutHandler: () -> Void

    init(
        onSuccessHandler: @escaping (String) -> Void,
        onErrorHandler: @escaping (String) -> Void,
        onAccountLoadedHandler: @escaping (Bool) -> Void,
        onSignOutHandler: @escaping () -> Void
    ) {
        self.onSuccessHandler = onSuccessHandler
        self.onErrorHandler = onErrorHandler
        self.onAccountLoadedHandler = onAccountLoadedHandler
        self.onSignOutHandler = onSignOutHandler
    }

    func onSuccess(accessToken: String) {
        onSuccessHandler(accessToken)
    }

    func onError(error: String) {
        onErrorHandler(error)
    }

    func onAccountLoaded(hasAccount: Bool) {
        onAccountLoadedHandler(hasAccount)
    }

    func onSignOutComplete() {
        onSignOutHandler()
    }
}

/// Extension to register the MSAL bridge with Kotlin
/// Call this during app initialization
public func registerMSALBridgeWithKotlin() {
    IOSMSALBridgeProvider.shared.bridge = MSALBridgeAdapter.shared
}

